# News / Updates
news:
  - date: "2026-03"
    content:
      en: "I will soon join [**Huawei Intelligent Automotive Solution BU**](https://auto.huawei.com/cn/) in Shanghai as an AI Software Engineer. 🎉"
      zh: "我即将加入[**华为智能汽车解决方案BU**](https://auto.huawei.com/cn/)（上海），担任AI软件开发工程师. 🎉"

  - date: "2025-07"
    content:
      en: "Won [**Second Prize (Top 2%)**]() in Software Application and Development at the 18th Chinese Collegiate Computing Competition! 🎉"
      zh: "在第十八届中国大学生计算机设计大赛软件应用与开发类中获得[**全国二等奖 (Top 2%)**](assets/files/4C_PPT.pdf)！ 🎉"

  - date: "2025-03"
    content:
      en: "Paper **'Hyper-Relation Fusion for Solving Multi-depot Vehicle Routing Problems'** accepted by **IJCNN 2025 (Oral)**!🎉"
      zh: "论文**'Hyper-Relation Fusion for Solving Multi-depot Vehicle Routing Problems'**被**IJCNN 2025（口头报告）**录用！🎉"

  - date: "2024-07"
    content:
      en: "Completed internship at [**Wuxi Future Technology Joint Research Center**](https://www.wnd.gov.cn/doc/2024/09/04/4385960.shtml)! 🎉"
      zh: "在[**无锡未来技术联合研究中心**](https://www.wnd.gov.cn/doc/2024/09/04/4385960.shtml)完成实习！ 🎉"

  - date: "2024-06"
    content:
      en: "Won [**Taihu Future Technology Innovation Award (Top 3%)**](https://www2.scut.edu.cn/ft/2024/0614/c29758a556527/page.htm) by Wuxi government! 🎉"
      zh: "获得无锡市政府颁发的[**太湖未来技术创新奖 (Top 3%)**](https://www2.scut.edu.cn/ft/2024/0614/c29758a556527/page.htm)！ 🎉"